# Generated by Django 5.1.7 on 2026-09-05 06:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='一句话定位')),
                ('avatar', models.ImageField(blank=True, upload_to='profile/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='自我介绍')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('blog_url', models.URLField(blank=True, verbose_name='博客链接')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
            },
            bases=(core.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='我的博客', max_length=100, verbose_name='站点名')),
                ('site_description', models.CharField(blank=True, max_length=200, verbose_name='站点描述')),
                ('footer_text', models.CharField(blank=True, max_length=200, verbose_name='页脚文案')),
                ('job_seeking', models.BooleanField(default=False, verbose_name='求职中')),
                ('job_status_text', models.CharField(blank=True, max_length=100, verbose_name='求职状态文案')),
                ('job_target', models.CharField(blank=True, max_length=200, verbose_name='目标方向')),
                ('job_available', models.BooleanField(default=False, verbose_name='可到岗')),
                ('resume_file', models.FileField(blank=True, upload_to='resume/', verbose_name='简历 PDF')),
                ('career_category_slug', models.CharField(default='career', max_length=100, verbose_name='求职感悟分类 slug')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
            bases=(core.models.SingletonMixin, models.Model),
        ),
    ]
