# Generated by Django 5.1.7 on 2026-09-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='相册名')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='别名')),
                ('cover', models.ImageField(blank=True, upload_to='albums/', verbose_name='封面图')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='标题')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='图片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('taken_at', models.DateField(blank=True, null=True, verbose_name='拍摄时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.album', verbose_name='相册')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['order', '-taken_at', 'id'],
            },
        ),
    ]
