# Generated by Django 5.1.7 on 2026-09-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('work', '工作'), ('education', '教育'), ('milestone', '项目里程碑')], default='work', max_length=20, verbose_name='类型')),
                ('org', models.CharField(max_length=120, verbose_name='机构/公司')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='角色/职位')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, help_text='留空表示至今', null=True, verbose_name='结束时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '经历时间线',
                'verbose_name_plural': '经历时间线',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='项目名')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True, verbose_name='别名')),
                ('summary', models.CharField(max_length=200, verbose_name='一句话简介')),
                ('description', models.TextField(blank=True, verbose_name='详细介绍（Markdown）')),
                ('tech_stack', models.CharField(blank=True, help_text='逗号分隔，如：Python,Django,爬虫', max_length=200, verbose_name='技术栈')),
                ('cover', models.ImageField(blank=True, upload_to='projects/', verbose_name='封面图')),
                ('url', models.URLField(blank=True, verbose_name='项目地址')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_featured', models.BooleanField(default=False, verbose_name='置顶/精选')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-is_featured', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='技能名称')),
                ('category', models.CharField(blank=True, help_text='如：语言 / 框架 / 数据库 / 工具与部署', max_length=50, verbose_name='分类')),
                ('level', models.PositiveSmallIntegerField(default=3, verbose_name='熟练度(1-5)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
